### ISSUE TITLE
Why now this style?

### ISSUE THREAD

**Issue by kud** [Hiswe/gulp-svg-symbols#23]
`style="width:0; height:0; visibility:hidden;"`

Why now this style and not `display: none` like before?

It does that on my website:

![u6hiujd4n1](https://cloud.githubusercontent.com/assets/655838/11631640/40daac10-9d03-11e5-9af7-f4b1aceb66c9.png)

As you can see, there's a line now where it was not before.

**Comment by Hiswe** [comment]
@kud It's because a `display: none` can mess with `<defs>`, like applying a SVG drop-shadow or gradients.
When I say mess, it's that the effects won't be applied at all :)

It should be preferable to do something like this:

```css
body > svg {
  border: 0 !important;
  clip: rect(0 0 0 0) !important;
  height: 1px !important;
  margin: -1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}
```

I should remove the inline style from the default template, and let you use tour preferred hiding system. 
And btw, as svg external support comes better and better, the plugin shouldn't put presentational styles in the symbol file.
